# Generated by Django 2.0.1 on 2018-01-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_productinbasket_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinbasket',
            name='product',
        ),
        migrations.AddField(
            model_name='productinbasket',
            name='product_id',
            field=models.IntegerField(default=None),
        ),
    ]
